In [2]:
# NumPy is used for array-based transportation KPI analysis.
import numpy as np

#each row is a transportation route and each column represents Week 1–Week 5
otif = np.array([
    [94, 96, 91, 95, 97],   # Ahmedabad - Mumbai
    [89, 92, 90, 88, 91],   # Pune - Mumbai
    [96, 95, 97, 98, 96],   # Delhi - Jaipur
    [87, 90, 85, 89, 88]    # Mumbai - Bengaluru
])

In [7]:
print(f"OTIF: \n{otif}")

OTIF: 
[[94 96 91 95 97]
 [89 92 90 88 91]
 [96 95 97 98 96]
 [87 90 85 89 88]]


In [8]:
print(f"Shape: {np.shape(otif)}")

Shape: (4, 5)


In [9]:
print(f"Dimension: {np.ndim(otif)}")

Dimension: 2


In [10]:
print(f"Size: {np.size(otif)}")

Size: 20


In [11]:
print(f"Overall average OTIF% : {np.mean(otif)}")

Overall average OTIF% : 92.2


In [14]:
print("Route-wise average OTIF%:\n")
print(np.mean(otif,axis=1))

Route-wise average OTIF%:

[94.6 90.  96.4 87.8]


In [15]:
print(f"Lowest route OTIF%: {min(np.mean(otif,axis=1))}")

Lowest route OTIF%: 87.8


In [17]:
# Measure each route's OTIF gap versus the overall benchmark.
route_variance = np.mean(otif,axis=1) - np.mean(otif)
print("Route Variance vs overall OTIF\n")
print(route_variance)

Route Variance vs overall OTIF

[ 2.4 -2.2  4.2 -4.4]


In [19]:
# Measure each route's OTIF gap versus the overall benchmark.
print("Routes below overall OTIF benchmark")
print(route_variance<0)

Routes below overall OTIF benchmark
[False  True False  True]


In [28]:
# Measure each route's OTIF gap versus the overall benchmark.
negative_variance = route_variance[1:4:2]

print(f"OTIF variance below benchmark: {negative_variance}")

OTIF variance below benchmark: [-2.2 -4.4]


In [29]:
# Select the negative gaps representing underperforming routes.
performance_gap = -1 * negative_variance
print(performance_gap)

[2.2 4.4]


In [33]:
# Express the underperformance gap as a positive magnitude.
print(f"largest OTIF gap: {round(np.max(performance_gap),1)}")

largest OTIF gap: 4.4


In [34]:
# Transportation routes used for route-level performance analysis.
routes = np.array([
    "Ahmedabad - Mumbai",
    "Pune - Mumbai",
    "Delhi - Jaipur",
    "Mumbai - Bengaluru"
])

In [35]:
# Measure each route's OTIF gap versus the overall benchmark.
# Identify routes performing below the overall OTIF benchmark
below_benchmark = route_variance < 0

# Extract route names and their OTIF averages
print(f"Routes below benchmark: {routes[below_benchmark]}")
print(f"OTIF performance of below-benchmark routes: {np.mean(otif, axis=1)[below_benchmark]}")

Routes below benchmark: ['Pune - Mumbai' 'Mumbai - Bengaluru']
OTIF performance of below-benchmark routes: [90.  87.8]


In [37]:
# Calculate the overall OTIF benchmark across all routes and weeks.
route_average = np.mean(otif, axis=1)
overall_average = np.mean(otif)
route_variance = route_average - overall_average

In [38]:
# OTIF data by route (rows) and week (columns).
# Find the index of the route with the lowest average OTIF
worst_route_index = np.argmin(route_average)

# Identify the worst-performing route
worst_route = routes[worst_route_index]

# Get its average OTIF and gap vs overall benchmark
worst_route_otif = route_average[worst_route_index]
worst_route_gap = route_variance[worst_route_index]

print(f"Worst-performing route: {worst_route}")
print(f"Average OTIF: {worst_route_otif:.1f}%")
print(f"Gap vs overall benchmark: {worst_route_gap:.1f} percentage points")

Worst-performing route: Mumbai - Bengaluru
Average OTIF: 87.8%
Gap vs overall benchmark: -4.4 percentage points


In [39]:
# Measure each route's OTIF gap versus the overall benchmark.
significantly_below = route_variance <= -2

print(f"Routes significantly below benchmark: {significantly_below}")

Routes significantly below benchmark: [False  True False  True]


In [40]:
# Calculate average OTIF for each week across all routes.
weekly_average = np.mean(otif, axis=0)

print(f"Weekly average OTIF: {weekly_average}")

Weekly average OTIF: [91.5  93.25 90.75 92.5  93.  ]


In [41]:
# OTIF data by route (rows) and week (columns).
# Find the index of the week with the lowest OTIF
worst_week_index = np.argmin(weekly_average)

# Convert NumPy index to business week number
worst_week = worst_week_index + 1

# Get the OTIF value
worst_week_otif = weekly_average[worst_week_index]

print(f"Worst-performing week: Week {worst_week}")
print(f"Weekly OTIF: {worst_week_otif:.2f}%")

Worst-performing week: Week 3
Weekly OTIF: 90.75%


In [42]:
# Freight cost data in ₹'000 by route (rows) and week (columns).
freight_cost = np.array([
    [420, 430, 415, 440, 450],   # Ahmedabad - Mumbai
    [380, 390, 395, 400, 410],   # Pune - Mumbai
    [520, 510, 525, 530, 540],   # Delhi - Jaipur
    [610, 625, 635, 620, 645]    # Mumbai - Bengaluru
])

In [44]:
print("Freight Cost Matrix: ")
print(freight_cost)

print(f"Shape: {freight_cost.shape}")
print(f"Dimension: {freight_cost.ndim}")
print(f"Total Freight Cost: {np.sum(freight_cost)}")

Freight Cost Matrix: 
[[420 430 415 440 450]
 [380 390 395 400 410]
 [520 510 525 530 540]
 [610 625 635 620 645]]
Shape: (4, 5)
Dimension: 2
Total Freight Cost: 9890


In [45]:
# Freight cost data in ₹'000 by route (rows) and week (columns).
route_avg_freight_cost = np.mean(freight_cost, axis=1)

print(f"Route-wise average freight cost: {route_avg_freight_cost}")

Route-wise average freight cost: [431. 395. 525. 627.]


In [47]:
# Calculate average weekly freight cost for each route.
# Find the index of the route with the highest average freight cost
highest_cost_index = np.argmax(route_avg_freight_cost)

# Identify the route
highest_cost_route = routes[highest_cost_index]

# Get its average freight cost
highest_cost = route_avg_freight_cost[highest_cost_index]

print(f"Highest-cost route: {highest_cost_route}")
print(f"Average freight cost: {highest_cost}")

Highest-cost route: Mumbai - Bengaluru
Average freight cost: 627.0


In [48]:
# OTIF data by route (rows) and week (columns).
cost_to_otif = route_avg_freight_cost / route_average

print(f"Cost-to-OTIF ratio: {cost_to_otif}")

Cost-to-OTIF ratio: [4.55602537 4.38888889 5.44605809 7.14123007]


In [49]:
# Freight cost data in ₹'000 by route (rows) and week (columns).
weekly_avg_freight_cost = np.mean(freight_cost, axis=0)

print(f"Weekly average freight cost: {weekly_avg_freight_cost}")

Weekly average freight cost: [482.5  488.75 492.5  497.5  511.25]


In [50]:
# Calculate average freight cost for each week across all routes.
# Find the index of the week with the highest average freight cost
highest_cost_week_index = np.argmax(weekly_avg_freight_cost)

# Convert index to business week number
highest_cost_week = highest_cost_week_index + 1

# Get the average freight cost
highest_week_cost = weekly_avg_freight_cost[highest_cost_week_index]

print(f"Highest-cost week: Week {highest_cost_week}")
print(f"Average freight cost: {highest_week_cost}")

Highest-cost week: Week 5
Average freight cost: 511.25


In [51]:
# OTIF data by route (rows) and week (columns).
# Identify routes with both below-benchmark OTIF and above-average freight cost
high_cost_low_otif = (
    (route_variance < 0) &
    (route_avg_freight_cost > np.mean(route_avg_freight_cost))
)

print(f"High-cost, low-OTIF routes: {high_cost_low_otif}")

High-cost, low-OTIF routes: [False False False  True]


In [52]:
# Transportation routes used for route-level performance analysis.
# Final business finding
priority_routes = routes[high_cost_low_otif]

print("Final Business Finding:")
print(f"Priority route(s): {priority_routes}")
print("These routes have both below-benchmark OTIF and above-average freight cost.")

Final Business Finding:
Priority route(s): ['Mumbai - Bengaluru']
These routes have both below-benchmark OTIF and above-average freight cost.


Final Business Summary

- Overall transportation OTIF performance was assessed across routes and weeks.
- Route-level analysis identified underperforming transportation lanes.
- Freight cost analysis highlighted high-cost routes and weeks.
- Mumbai - Bengaluru emerged as the key priority route, combining below-benchmark OTIF performance with above-average freight cost.
- This indicates an opportunity to investigate the route for potential service and transportation-cost improvement.