In [9]:
import numpy as np
production = np.array([    #week wise production planning
    [500,550,600,580],     #Product A
    [300,320,350,340],     #Prodcut B
    [450,470,490,520]      #Product C
])
print(f"Production Plan: {production}")
print(f"Shape: {np.shape(production)}")
print(f"Dimension: {np.ndim(production)}")

Production Plan: [[500 550 600 580]
 [300 320 350 340]
 [450 470 490 520]]
Shape: (3, 4)
Dimension: 2


In [10]:
print(f"Total Production: {np.sum(production)}")
print(f"Average Production: {round(np.mean(production),2)}")

Total Production: 5470
Average Production: 455.83


In [14]:
print(f"Weekly production: {np.sum(production,axis=0)}")

Weekly production: [1250 1340 1440 1440]


In [15]:
print(f"Product wise production per month: {np.sum(production, axis=1)}")

Product wise production per month: [2230 1310 1930]


In [21]:
new_production = 1.1*production
print(f"Current production: {production}")
print(f"Current total production: {np.sum(production)}\n")
print(f"Production after 10% increase: {new_production}")
print(f"Total production after 10% increase: {np.sum(new_production)}\n")
print(f"Total production increase: {np.sum(new_production)-np.sum(production)}")

Current production: [[500 550 600 580]
 [300 320 350 340]
 [450 470 490 520]]
Current total production: 5470

Production after 10% increase: [[550. 605. 660. 638.]
 [330. 352. 385. 374.]
 [495. 517. 539. 572.]]
Total production after 10% increase: 6017.0

Total production increase: 547.0


In [22]:
print(f"Product A's Week 3 production = {production[0,2]}")

Product A's Week 3 production = 600


In [23]:
print(f"Product C's Week 2 production = {production[2,1]}")

Product C's Week 2 production = 470


In [26]:
print(f"Week 2 and week 3 for all products: {production[:,1:3]}")

Week 2 and week 3 for all products: [[550 600]
 [320 350]
 [470 490]]


In [29]:
capacity = np.array([       #production capacity
    [550, 550, 650, 600],
    [350, 350, 350, 350],
    [500, 500, 500, 550]
])

In [32]:
print(f"Total Available Capacity: {np.sum(capacity) - np.sum(production)}")

Total Available Capacity: 330


In [31]:
available_capacity = capacity - production
print(f"Capacity : {capacity}\n")
print(f"Planned Production: {production}\n")
print(f"Available Capacity: {available_capacity}")

Capacity : [[550 550 650 600]
 [350 350 350 350]
 [500 500 500 550]]

Planned Production: [[500 550 600 580]
 [300 320 350 340]
 [450 470 490 520]]

Available Capacity: [[50  0 50 20]
 [50 30  0 10]
 [50 30 10 30]]


In [33]:
shipments = np.array([
    [420, 450, 480, 460, 500],   # Ahmedabad DC
    [350, 370, 390, 410, 430],   # Pune DC
    [280, 300, 320, 310, 340],   # Mumbai DC
    [500, 520, 540, 560, 580]    # Delhi DC
])

In [34]:
print(f"Shape: {np.shape(shipments)}")
print(f"Dimension: {np.ndim(shipments)}")
print(f"Total number of shipment records: {np.size(shipments)}")

Shape: (4, 5)
Dimension: 2
Total number of shipment records: 20


In [39]:
print(f"Pune DC across all 5 weeks: {shipments[1,:]}")

Pune DC across all 5 weeks: [350 370 390 410 430]


In [42]:
print(f"Week 2 through Week 4 for all 4 DCs: {shipments[:,1:4]}")

Week 2 through Week 4 for all 4 DCs: [[450 480 460]
 [370 390 410]
 [300 320 310]
 [520 540 560]]


In [43]:
print(f"Pune DC and Mumbai DC shipments during Week 3 to Week 5: {shipments[1:3,2:]}")

Pune DC and Mumbai DC shipments during Week 3 to Week 5: [[390 410 430]
 [320 310 340]]


In [46]:
supplier_performance = np.array([        #Columns:Lead, OTIF, Quality, Price Var, Defect
    [8, 95, 98,  2, 1],    # Supplier A
    [12, 88, 94,  5, 3],   # Supplier B
    [7,  97, 99,  1, 1],   # Supplier C
    [10, 91, 96,  4, 2]    # Supplier D
])

In [48]:
print(f"Supplier B and supplier C - all metrics: {supplier_performance[1:3,:]}")

Supplier B and supplier C - all metrics: [[12 88 94  5  3]
 [ 7 97 99  1  1]]


In [50]:
print(f"OTIF % and Quality % for all four suppliers: {supplier_performance[:,1:3]}")

OTIF % and Quality % for all four suppliers: [[95 98]
 [88 94]
 [97 99]
 [91 96]]


In [51]:
print(f"Supplier B and Supplier C - OTIF % and Quality %: {supplier_performance[1:3,1:3]}")

Supplier B and Supplier C - OTIF % and Quality %: [[88 94]
 [97 99]]


In [52]:
print(f"Supplier C and Supplier D - Quality, Price Variance, Defect Rate: {supplier_performance[2:,2:]}")

Supplier C and Supplier D - Quality, Price Variance, Defect Rate: [[99  1  1]
 [96  4  2]]
